### ISSUE TITLE
Specific zsh configuration never load

### ISSUE THREAD

**Issue by nandordudas** [qdm12/basedevcontainer#5]
https://github.com/qdm12/basedevcontainer/blob/33332f54d7f613c7149038f5078032bf82fd0676/shell/.zshrc#L45

Extension not needed.

Am I right?

**Comment by qdm12** [comment]
Yes it is in downstream images based on this one.

[Example](https://github.com/qdm12/godevcontainer/blob/master/shell/.zshrc-specific)

Out of curiosity, what's your usage of this base dev container? 🤔

**Comment by nandordudas** [comment]
> Out of curiosity, what's your usage of this base dev container? 🤔

I just tried it with devcontainer.
