### ISSUE TITLE
Build error - mounting git folder.

### ISSUE THREAD

**Issue by KevinRohn** [qdm12/basedevcontainer#8]
Hi @qdm12 ,

I really appreciate your work!

I try to get the container to run on my raspberry Pi (armv7l).

But I always get the following error:

```
ecreating devcontainer_vscode_1 ... error

ERROR: for devcontainer_vscode_1  Cannot start service vscode: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/.gitconfig" to rootfs at "/root/.gitconfig" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for vscode  Cannot start service vscode: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/.gitconfig" to rootfs at "/root/.gitconfig" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

Could you help me out on this problem?

Thank you in advance

**Comment by qdm12** [comment]
what's your run configuration?

If you don't want to use a gitconfig file you can just remove the volume bind mount in docker-compose.yml.

If I may ask as well, what's your use case for this image? I personally use it only as a base image for other images like https://github.com/qdm12/godevcontainer

**Comment by KevinRohn** [comment]
Hello @qdm12,

thank you for reaching out to me.

My usecase is to develop a nodejs applicaton on raspberry pi (armv7l) by using github remote containers.
I also found your node .devcontainer repo. But I get the same error. I will get back to you later today with the configuration file.

cheers,
kevin

**Comment by qdm12** [comment]
I'll update that nodedevcontainer, I didn't update it for a while :fearful:

**Comment by qdm12** [comment]
I think you should have a more up-to-date image now at https://github.com/qdm12/nodedevcontainer

**Comment by KevinRohn** [comment]
thank you @qdm12
