### ISSUE TITLE
Buster Package Lists are 'oldstable'

### ISSUE THREAD

**Issue by moritzj29** [qdm12/basedevcontainer#9]
First of all thanks for this docker image, it is a great help!

Just in case anyone stumbles onto that:

Debian Buster is no longer the current `stable` release, therefore simple `apt-get` calls to extend the image do not work. Just add the `--allow-releaseinfo-change` flag to the update command:
```
RUN apt-get --allow-releaseinfo-change update -y
```
Of course an updated image would be great, but for now this fix does the trick!

**Comment by moritzj29** [comment]
never mind, this is only relevant for images based on old `basedevcontainer` builds.

**Comment by qdm12** [comment]
Sorry for replying so late, I'm glad you figured it out!

Although the debian images are still based on `buster-slim`, I just updated them to use `bullseye-slim`. The reason it was buster is because some packages (like old Java) are only available there 😢
